languageCode = "en-us"
title = "Jewell.Solutions"
baseurl = "http://jewell.solutions/"
theme = "aerial"

[params]
  logo = "https://s3.amazonaws.com/jewell.solutions/logo.png"
  name = ""
  about = "Streamline who you go to and utilize my full-stack omnichannel commerce solutions. Contact to see how I can help with your small business' content creation, marketing, and technology."
  copyright = "2018 Jewell.Solutions"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = "false"
  favicon = "favicon.ico"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/kylejewell"

[[params.social]]
  medium = "LinkedIn"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/kylejewell/"

[[params.social]]
  medium = "Email"
  icon = "paper-plane"
  link = "mailto:kyle@jewell.solutions"
