languageCode = "en-us"
title = "Jewell.Solutions"
baseurl = "http://jewell.solutions/"
theme = "aerial"

[params]
  name = "Jewell.Solutions"
  about = "Providing a full stack approach to omnichannel commerce consulting.<br>Streamline who you go to, contact me to see how I can grow your small business."
  copyright = "2018"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/kylejewell"

[[params.social]]
  medium = "LinkedIn"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/kylejewell/"

[[params.social]]
  medium = "Email"
  icon = "paper-plane"
  link = "mailto:kyle@jewell.solutions"
